version: "3.7"
services:
    pkg:
        build:
           context: .
           dockerfile: Dockerfile
        container_name: motivatieservice
        ports:
            - "0.0.0.0:5009:5009"
        networks:
            - twatter-network

networks:
    twatter-network:
        external: true
